### PR TITLE
REALMC-6733: Add bson types to readme

### PR DESCRIPTION
**Pull request by haleyowen**

### CODE REVIEW

**Review by tsedgwick — APPROVED** [review]
is this all that was needed to update the readme?

**Comment by tsedgwick** [comment]
branch is still called stitch and not baas? 🙊

**Comment by haleyowen** [comment]
> branch is still called stitch and not baas? 🙊

shhhhhhhhhhhh

**Comment by haleyowen** [comment]
> is this all that was needed to update the readme?

i think sooooo? that's all i did lolol

**Pull request merged**
